# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extraction}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Solt"]
  s.date = %q{2011-04-04}
  s.description = %q{ActiveModel based (web) data extraction library. Work in progress.}
  s.email = %q{mattsolt@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "autotest.options",
    "autotest/discover.rb",
    "extraction.gemspec",
    "features/extraction.feature",
    "features/step_definitions/extraction_steps.rb",
    "features/support/env.rb",
    "lib/extraction.rb",
    "lib/extraction/attributes.rb",
    "lib/extraction/base.rb",
    "lib/extraction/middleware.rb",
    "lib/extraction/setup.rb",
    "lib/extraction/version.rb",
    "spec/active_model_shared.rb",
    "spec/cassettes/google_ruby_search.yml",
    "spec/extraction/base_spec.rb",
    "spec/extraction/html_extractor_spec.rb",
    "spec/extraction_spec.rb",
    "spec/models/extractor.rb",
    "spec/models/html_extractor.rb",
    "spec/models/link_extractor.rb",
    "spec/rspec.options",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/activefx/extraction}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ActiveModel based (web) data extraction library. Work in progress.}
  s.test_files = [
    "spec/active_model_shared.rb",
    "spec/extraction/base_spec.rb",
    "spec/extraction/html_extractor_spec.rb",
    "spec/extraction_spec.rb",
    "spec/models/extractor.rb",
    "spec/models/html_extractor.rb",
    "spec/models/link_extractor.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<extraction>, [">= 0"])
      s.add_runtime_dependency(%q<chronic>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_development_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_development_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_development_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_development_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.3.0"])
      s.add_development_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_development_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.3.0"])
      s.add_development_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_development_dependency(%q<evergreen>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.5"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_development_dependency(%q<yard>, [">= 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_development_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.3.0"])
    else
      s.add_dependency(%q<extraction>, [">= 0"])
      s.add_dependency(%q<chronic>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
      s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
      s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
      s.add_dependency(%q<evergreen>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<activemodel>, [">= 3.0.5"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<cucumber>, [">= 0.10.2"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<vcr>, [">= 1.7.2"])
      s.add_dependency(%q<yard>, [">= 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<jeweler>, [">= 1.5.2"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<hpricot>, [">= 0.8.4"])
      s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<extraction>, [">= 0"])
    s.add_dependency(%q<chronic>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<hpricot>, [">= 0.8.4"])
    s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<hpricot>, [">= 0.8.4"])
    s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
    s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<hpricot>, [">= 0.8.4"])
    s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
    s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<hpricot>, [">= 0.8.4"])
    s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
    s.add_dependency(%q<mynyml-redgreen>, [">= 0"])
    s.add_dependency(%q<evergreen>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<activemodel>, [">= 3.0.5"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<cucumber>, [">= 0.10.2"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<vcr>, [">= 1.7.2"])
    s.add_dependency(%q<yard>, [">= 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<jeweler>, [">= 1.5.2"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<hpricot>, [">= 0.8.4"])
    s.add_dependency(%q<lumberjack>, [">= 1.0.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.3.0"])
  end
end

